name: Testing
on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: src/github.com/nats-io/jsm.go

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          export GOPATH="$RUNNER_WORKSPACE"
          go get -v -u honnef.co/go/tools/cmd/staticcheck
          go get -v -u github.com/client9/misspell/cmd/misspell

      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          export GOPATH="$RUNNER_WORKSPACE"
          PATH=$PATH:$GOPATH/bin
          $(exit $(go fmt $(go list ./...) | wc -l))
          find . -type f -name "*.go" | grep -v "/vendor/" | xargs misspell -error -locale US
          staticcheck -f stylish $(go list ./...)
          go vet ./...

      - name: Run tests
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          export GOPATH="$RUNNER_WORKSPACE"
          go test -v -race -p 1 ./...
